### ISSUE TITLE
Plugin based disk image manager

### ISSUE THREAD

**Issue by noxdafox** [F-Secure/see#33]
Currently, only way to provide disk images to SEE is via the implicit use of a libvirt FS based storage pool. There are use cases in which the image could be provided via other means (example: raw FS or using a image manager such as [Glance](http://docs.openstack.org/developer/glance/).

To support that, we need to add a plugin based image manager. Most of the Hooks logic can be re-used (maybe moved into a generic module?).

A possible configuration interface:
```
"disk":
{
    "image": 
    {
        "uri": "/original/image/location",
        "provider": "python.fully.qualified.Name",
        "provider_configuration": {}
    },
    "clone":
    {
        "storage_pool_path": "/destination/storage/pool"
    }
}
```

Example using current mechanism.

```
"disk":
{
    "image": 
    {
        "uri": "/var/lib/libvirt/images/disk_image.qcow2",
        "provider": "context.resources.image_managers.LibvirtStoragePool",
        "provider_configuration": 
        {
            "storage_pool_path": ""/var/lib/libvirt/"
        }
    },
    "clone":
    {
        "storage_pool_path": "/home/user/see_instances",
        "copy_on_write": true
    }
}
```

**Comment by banjoh** [comment]
404 on https://github.com/F-Secure/see/issues/glance.openstack.org

**Comment by noxdafox** [comment]
Fixed, thanks

**Comment by Jorge-Rodriguez** [comment]
This is handled by #34

**Comment by noxdafox** [comment]
Merged and submitted to Pypi.
