### ISSUE TITLE
Unable to trigger VNC plugin/hook

### ISSUE THREAD

**Issue by jacob20** [F-Secure/see#42]
Hi, 

I was following the tutorial and at this [particular section](http://pythonhosted.org/python-see/tutorial_plugins.html) where the code to invoke VNC was abstracted to a separate plugin/hook. 
Despite following the steps, the execution does not seem to invoke the VNC plugin.

My current setup is described below: 

sandbox.py
`Same as what is presented at: http://pythonhosted.org/python-see/tutorial_plugins.html`

vnc.py
`Same as what is presented at: http://pythonhosted.org/python-see/tutorial_plugins.html`

context.json
```
{
    "hypervisor": "qemu:///system",
    "domain":
    {
        "configuration": "<path to config>.xml"
    },
    "disk":
    {
        "image":
        {
          "uri": "<path to diskimage>.qcow2",
          "provider": "see.image_providers.DummyProvider"
        },
        "clone":
        {
            "storage_pool_path": "<path to pool>/instances",
            "copy_on_write": true
        }
    }
}
```
hooks.json
```
{
    "hooks":
    [
        {
            "name": "vnc2.VNCHook",
            "configuration": {
                "start_vnc": "post_poweron"
            }
        }
    ]
}
```
All the files are in the same directory and at the same level. 
Upon executing 
`python sandbox.py context.json hello --hooks hooks.json --command "dummy-command"`

The sandbox instance starts but the vnc plugin and it's virt-viewer command doesn't seem to be triggered by the `post_poweron` event. In addition, there is a console message saying
`No handlers could be found for logger "see.hooks.HookManager"`

Am I missing something? I'm running this on a linux environment and my VM is a linux machine as well. virt-viewer was able to be started previously at [this step](http://pythonhosted.org/python-see/tutorial_hellosandbox.html)

Thank you for the help!

**Comment by noxdafox** [comment]
Hello,

The `HookManager` is responsible for loading the plugins. In case of a plugin failing to initialize, it will log the actual error. To do so, you need to enable logging in your script.

Just add the following code at the beginning of the `sandbox.py` script.

```python
import logging

logging.BasicConfig()
```

You should then see the actual error triggered when trying to initialize the VNC plugin. My bet is the plugin cannot be imported by the Python interpreter. In that case, you can fixing it by adding your plugin path to the `PYTHONPATH` environment variable.

**Comment by jacob20** [comment]
Thanks for the prompt response! As suggested, I've added logging
```
DEBUG:see.environment.Environment:Allocating environment.
DEBUG:see.hooks.HookManager:Loading vnc.VNCHook hook.
ERROR:see.hooks.HookManager:Hook vnc.VNCHook initialization failure, error: super() takes at least 1 argument (0 given).
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/see/hooks.py", line 70, in _load_hook
    context))
  File "<path>/vnc.py", line 20, in __init__
    super().__init__(parameters)
TypeError: super() takes at least 1 argument (0 given)
DEBUG:see.environment.Environment:Environment successfully allocated.
```
Google led me to [this](https://stackoverflow.com/questions/38963018/typeerror-super-takes-at-least-1-argument-0-given-error-is-specific-to-any). Taking reference, I modified line 20 to `super(VNCHook, self).__init__(parameters)` and the VNC plugin is now able to be loaded and initialized. 

Once again, thank you for the help!

**Comment by noxdafox** [comment]
The tutorial was written in Python 3 so some adjustment might be necessary to run it with Python 2.

Glad you solved the issue. I will close this ticket.
