### ISSUE TITLE
'NoneType' object has no attribute 'get' in Dummy provider

### ISSUE THREAD

**Issue by Wenzel** [F-Secure/see#59]
Hi,

I think you introduced a regression in the releases after 1.2.6.

Using `1.2.6` it works fine.
![Capture d’écran de 2019-08-25 15-33-56](https://user-images.githubusercontent.com/964610/63650726-3b6ebb80-c74e-11e9-9945-d39d32e932c9.png)

My program doesn't work anymore (with `1.2.12`, latest release)
![Capture d’écran de 2019-08-25 15-34-15](https://user-images.githubusercontent.com/964610/63650711-15e1b200-c74e-11e9-8f44-4382b852de7b.png)

Thanks.

**Comment by Wenzel** [comment]
It looks like `self.configuration` doesn't exist in `DummyProvider` object:
https://github.com/F-Secure/see/blob/master/see/image_providers/dummy.py#L31

Which should be initialized by this:
https://github.com/F-Secure/see/blob/master/see/interfaces.py#L45

~~~Python
class ImageProvider(object):
    """Abstract base class for image provider backends."""
    def __init__(self, parameters):
        super(ImageProvider, self).__init__()
        self.configuration = parameters.get('provider_configuration')
        self.name = parameters.get('name')
~~~

**Comment by Wenzel** [comment]
This is how I'm initializing SEE in OSWatcher:
https://github.com/Wenzel/oswatcher/blob/master/oswatcher/capture.py#L35

~~~Python

class QEMUDomainContextFactory(QEMUContextFactory):
....
....
        context_config = {
            "hypervisor": uri,
            "domain": {
                "configuration": self.domain_tmp_f.name
            },
            "disk": {
                "image": {
                    "uri": qcow_path,
                    "provider": "see.image_providers.DummyProvider"
                },
                "clone": {
                    "storage_pool_path": self.osw_storage_path.name,
                    "copy_on_write": True
                }
            }
        }
        super().__init__(context_config)
~~~

**Comment by Wenzel** [comment]
The bug has been introduced by the `1.2.9` release

**Comment by Jorge-Rodriguez** [comment]
@Wenzel The configuration structure has changed to unify all providers, You need to configure your dummy provider explicitly as you would any other, e.g.:
```
           "disk": {
                "image": {
                    "provider": "see.image_providers.DummyProvider",
                    "provider_configuration": {
                        "path": qcow_path
                     }
                 }
              },

**Comment by Jorge-Rodriguez** [comment]
Come to think about it, this does break backwards compatibility and you could argue that version 1.2.9 should be 1.3.0 instead

**Comment by Wenzel** [comment]
@Jorge-Rodriguez i needed to add a `name` field too:

~~~Python
        # find domain qcow path
        qcow_path = Path(get_hard_disk(domain))

        context_config = {
            "hypervisor": uri,
            "domain": {
                "configuration": self.domain_tmp_f.name
            },
            "disk": {
                "image": {
                    "provider": "see.image_providers.DummyProvider",
                    "provider_configuration": {
                        "path": qcow_path.parent,
                    },
                    "name": qcow_path.name,
                },
                "clone": {
                    "storage_pool_path": self.osw_storage_path.name,
                    "copy_on_write": True
                }
            }
        }
~~~

this works.
feel free to close the issue.

thanks for your help :)

**Comment by Jorge-Rodriguez** [comment]
Since this breaks backwards compatibility, I will re-release version 1.2.12 as 1.3.0 and remove everything between that an 1.2.8
